### ISSUE TITLE
Ошибка в linux

### ISSUE THREAD

**Issue by osscombat** [bol-van/smotreshka-ripper#1]
Пробую на php 7.3:
Exception: http code 403 in https://fe.smotreshka.tv/login

**Comment by bol-van** [comment]
Неверный login/password , блокированная учетка или что-то такое
С рабочим логином работает на php 7.3

**Comment by osscombat** [comment]
но в качестве логина ещё есть номер телефона, на сайте он работает

**Comment by bol-van** [comment]
у меня работает с email. с телефоном не пробовал. возможно, требуется определенный формат номера

**Comment by osscombat** [comment]
похоже у них больше не зарегистрироваться по email, только по номеру телефона

**Comment by bol-van** [comment]
у меня аккаунты с провайдера. не напрямую

**Comment by bol-van** [comment]
fixed.  там всего лишь требовался urlencode в email
'+' => '%2B'

**Comment by osscombat** [comment]
теперь другое:
`PHP Fatal error:  Uncaught Error: Call to undefined function json_decode() in smotreshka.php:87
Stack trace:
#0 {main}
  thrown in smotreshka.php on line 87`
