### ISSUE TITLE
ошибка в linux

### ISSUE THREAD

**Issue by osscombat** [bol-van/smotreshka-ripper#2]
На аккаунте без подписок, только с доступными тестовыми каналами теперь пишет:

`PHP Fatal error: Uncaught Error: Call to undefined function json_decode() in smotreshka.php:87 
Stack trace: #0 {main} thrown in smotreshka.php on line 87`

**Comment by bol-van** [comment]
отсутствуют php7.3-json php7.3-curl

**Comment by osscombat** [comment]
точно, php-json. Cупер, большое спасибо!
