### ISSUE TITLE
403 error

### ISSUE THREAD

**Issue by igoralexeev** [bol-van/smotreshka-ripper#3]
Exception: http code 403 in https://fe.smotreshka.tv/login
PHP Error
Для продолжения нажмите любую клавишу . . .

все установлено вроде бы верно

но...
есть логин от смотрешки и есть емейл, пробовал и так и так. может что то поменялось у них? Очень хочется плейлист. айпишник к тому же статичный у меня

спасибо!

**Comment by bol-van** [comment]
Может аккаунт накрылся ?
У меня есть 2 аккаунта, оба работают, проверил на 2 системах

Вот так можно без PHP дернуть их login
curl "https://fe.smotreshka.tv/login" -d "email=емейл&password=пароль"

**Comment by igoralexeev** [comment]
В аккаунт вхожу через сайт. Но через номер телефона или логин, хотя и е-мейл тоже привязан.  Ещё попробую

**Comment by igoralexeev** [comment]
Invoke-WebRequest : Не удается найти позиционный параметр, принимающий аргумент "email=rulezman@gmail.com&password=####".
строка:1 знак:1

**Comment by bol-van** [comment]
Потрудитесь разъяснить откуда получено это сообщение и при каких действиях

**Comment by igoralexeev** [comment]
запустил  curl "https://fe.smotreshka.tv/login" -d "email=емейл&password=пароль" как вы и рекомендовали ранее

**Comment by bol-van** [comment]
Invoke-WebRequest это что-то из powershell
powershell каким-то образом переделывает вызовы curl в Invoke-WebRequest
следует запускать из cmd, имея curl.exe
или если все-же powershell, то сделать Remove-item alias:curl
