### ISSUE TITLE
error 404

### ISSUE THREAD

**Issue by usersmotreshka** [bol-van/smotreshka-ripper#4]
16 ноября 2023 стала появляться ошибка и плейлист не качается 
Exception: http code 404 in https://fe.smotreshka.tv/playback-info/54eafa284e2e6719290377de

**Comment by bol-van** [comment]
Видимо ошибка самого сервиса. Выдается, что канал куплен, но при попытке его дернуть - как будто не куплен.
Сделал так, чтобы в этом случае процессинг не прерывался, а канал игнорировался

**Comment by usersmotreshka** [comment]
Спасибо. помогло
