### ISSUE TITLE
Exception: http code 500 in https://fe.smotreshka.tv/login

### ISSUE THREAD

**Issue by xxxDZxxx** [bol-van/smotreshka-ripper#5]
я так понял они поменяли точку входа

https://fe.smotreshka.tv/login - 404 page not found =(

**Comment by bol-van** [comment]
У меня работает. Этот URL работает только по методу POST, на GET действительно выдает 404

**Comment by xxxDZxxx** [comment]
Так и не получилось запустить... на винде все тот же 500. Развернул на линуксе, там аргумент не нравится
`PHP Warning:  Undefined variable $argc in /var/www/html/2/smotreshka.php on line 7`

**Comment by bol-van** [comment]
это надо запускать через   php-cli,  а не как скрипт веб сервера

**Comment by xxxDZxxx** [comment]
Спасибо огромное! все получилось... Осталось только php на libreelec как-то повесить и будет пенсионерам счастье! =)  Можно еще 2 вопроса... 
1) EPG /  xmltv возможно брать со смотрешки или искать где-то сторонние?
2)  Если накидать 15-20 каналов в избранное через сайт, возможно только их забирать ?
ps. еще раз спасибо! =)))

**Comment by xxxDZxxx** [comment]
Подскажите, а на wink нечто похожее возможно ?

**Comment by bol-van** [comment]
Не знаю, не изучал.
Эту софтину сделал давным давно, когда провайдер предлагал бесплатный пакет.
Но пользоваться веб сайтом неудобно, хотел на KODI
